### ISSUE TITLE
Upload logs Problem

### ISSUE THREAD

**Issue by xfouloux** [guy0090/LostArkLogs#4]
When i try to upload logs (or on https://lail.ai/ulog for that matters)
i get a : Failed to upload: Invalid Request

in logs i can see 

```
api      | 2022-08-11 07:26:54 error: [POST] /logs/raw/upload >> StatusCode:: 400, Message:: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
```

**Comment by xfouloux** [comment]
had to add to docker-compose.yml this for mongo service 
`command: --replSet rs0`

so it looks like this 
```
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '127.0.0.1:27016:27017'
    networks:
      - backend
    volumes:
      - ./mongo/data:/data/db
    command: --replSet rs0
```
then after start, 
```
# docker exec -it mongo bash
root@3c2dce1d9bb0:/# mongo 
> rs.initiate() 
```
to init the mongo replica
then
`docker-compose restart`

now i can send uploads, without having mongo failing, but another issue arrise.

```
api      | 2022-08-12 00:15:14 error: [POST] /logs/raw/upload >> StatusCode:: 400, Message:: Cannot read property 'totalHealingDone' of undefined 
```
